### ISSUE TITLE
CROSS COMPILE FOR ARM.

### ISSUE THREAD

**Issue by lewiz-sunny** [erimatnor/aodv-uu#1]
Hello,
I want to cross compile the AODV code for arm which has 4.15.0-106-generic kernel. Can you please guide me the changes I need to do, in order to make it work on arm device?

Thank you.

**Comment by mwarning** [comment]
This might help: https://github.com/lixiangyuan98/aodv-uu/commits/master

**Comment by lewiz-sunny** [comment]
@mwarning Thank you for redirecting me. That helped me with the cross compilation but, it does not compile the kernel module, I mean install the kernel module. Is there anyway to make it work on ARM64?

**Comment by mwarning** [comment]
If you target is Linux Kernel 5.0.0 and the link above does not help, then either downgrade the kernel (Debian Lenny, https://github.com/erimatnor/aodv-uu/pull/5/files) of your target or you can try my aodv-uu fork (https://github.com/mwarning/aodv-uu) - but I haven't actually tested it yet.

**Comment by mwarning** [comment]
If your problem is that your host kernel is not your target kernel, then I probably cannot help you. I haven't tried that.

**Comment by lewiz-sunny** [comment]
@mwarning I tried your code but it gave me an error when I do cross compilation: (make arm). Also I removed the bigendian flag.

make[1]: *** No rule to make target 'kaodv-arm'.  Stop.

I just want to cross compile on my host kernel which is 4.15.0-106-generic

**Comment by mwarning** [comment]
Yes, I removed a lot of old build stuff. You would need to fix it for your setup.

**Comment by lewiz-sunny** [comment]
@mwarning I am very new to this, so sorry if my question is not relevant. Do you happen to know about this error?

./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>

**Comment by mwarning** [comment]
Try to comment out that include line. If that does not work, check if the file is present somewhere else in ./include/uapi/linux/. If that else fails, fix the errors that happen when you have removed the include lines.
